CREATE TABLE Airline_Delay_Cause (
    year Uint64,
    month Uint64,
    carrier Utf8,
    carrier_name Utf8,
    airport Utf8,
    airport_name Utf8,
    arr_flights Uint64,
    arr_del15 Uint64,
    carrier_ct Decimal(10,2),
    weather_ct Decimal(10,2),
    nas_ct Decimal(10,2),
    security_ct Decimal(10,2),
    late_aircraft_ct Decimal(10,2),
    arr_cancelled Uint64,
    arr_diverted Uint64,
    arr_delay Uint64,
    carrier_delay Uint64,
    weather_delay Uint64,
    nas_delay Uint64,
    security_delay Uint64,
    late_aircraft_delay Uint64,
    PRIMARY KEY (year, month, carrier, airport)
);